name: Docker Build and Run on Self-Hosted Runner

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          echo "Building Docker Image..."
          docker build -t webapp-build:latest .

      - name: Run Docker Container
        run: |
          echo "Running Docker Container..."
          docker rm webapp-container
          docker run -d -p 80:80 --name webapp-container webapp-build:latest

      - name: Verify Running Container
        run: |
          echo "Checking Running Containers..."
          docker ps -a
